Repository Team-hangout/backend, pull requests merged in 2023-07, with the labels that each got.

#57 Fix/56/handle cors
  src/main/java/com/hangout/hangout/global/config/SecurityConfig.java
  src/main/java/com/hangout/hangout/global/config/SwaggerConfig.java
Labels: 🐞 bug

#54 Feature/52/post hits
  build.gradle
  src/main/java/com/hangout/hangout/HangoutApplication.java
  src/main/java/com/hangout/hangout/domain/post/controller/PostController.java
  src/main/java/com/hangout/hangout/domain/post/entity/PostHits.java
  src/main/java/com/hangout/hangout/domain/post/entity/PostHitsRedis.java
  src/main/java/com/hangout/hangout/domain/post/repository/PostHitsRedisRepository.java
  src/main/java/com/hangout/hangout/domain/post/repository/PostHitsRepository.java
  src/main/java/com/hangout/hangout/domain/post/repository/PostHitsRepositoryQuerydsl.java
  src/main/java/com/hangout/hangout/domain/post/repository/PostHitsRepositoryQuerydslImpl.java
  src/main/java/com/hangout/hangout/domain/post/repository/PostRepositoryQuerydsl.java
  src/main/java/com/hangout/hangout/domain/post/repository/PostRepositoryQuerydslImpl.java
  src/main/java/com/hangout/hangout/domain/post/service/PostService.java
  src/main/java/com/hangout/hangout/global/common/domain/entity/CacheKey.java
  src/main/java/com/hangout/hangout/global/config/RedisConfig.java
  src/main/resources/application.yml
Labels: ✨ Feature

#55 Feature/53/image
  build.gradle
  src/main/java/com/hangout/hangout/domain/auth/dto/request/SignUpRequest.java
  src/main/java/com/hangout/hangout/domain/image/config/AmazonS3Config.java
  src/main/java/com/hangout/hangout/domain/image/controller/PostImageController.java
  src/main/java/com/hangout/hangout/domain/image/controller/UserImageController.java
  src/main/java/com/hangout/hangout/domain/image/entity/PostImage.java
  src/main/java/com/hangout/hangout/domain/image/entity/UserImage.java
  src/main/java/com/hangout/hangout/domain/image/exception/FileExceptionHandler.java
  src/main/java/com/hangout/hangout/domain/image/exception/UnSupportedFileTypeException.java
  src/main/java/com/hangout/hangout/domain/image/repository/ImageJdbcRepository.java
  src/main/java/com/hangout/hangout/domain/image/repository/PostImageRepository.java
  src/main/java/com/hangout/hangout/domain/image/repository/UserImageRepository.java
  src/main/java/com/hangout/hangout/domain/image/service/AwsS3Service.java
  src/main/java/com/hangout/hangout/domain/image/service/ImageFileUploadService.java
  src/main/java/com/hangout/hangout/domain/image/service/UserImageFileUploadService.java
  src/main/java/com/hangout/hangout/domain/image/util/FileType.java
  src/main/java/com/hangout/hangout/domain/image/util/FileUtils.java
  src/main/java/com/hangout/hangout/domain/like/service/LikeService.java
  src/main/java/com/hangout/hangout/domain/post/PostMapper.java
  src/main/java/com/hangout/hangout/domain/post/controller/PostController.java
  src/main/java/com/hangout/hangout/domain/post/dto/PostListResponse.java
  src/main/java/com/hangout/hangout/domain/post/dto/PostResponse.java
  src/main/java/com/hangout/hangout/domain/post/entity/PostInfo.java
  src/main/java/com/hangout/hangout/domain/report/controller/ReportController.java
  src/main/java/com/hangout/hangout/domain/user/controller/UserController.java
  src/main/java/com/hangout/hangout/domain/user/dto/UserResponse.java
  src/main/java/com/hangout/hangout/domain/user/entity/User.java
  src/main/java/com/hangout/hangout/domain/user/service/UserService.java
  src/main/java/com/hangout/hangout/global/error/ResponseType.java
  src/main/resources/application.yml
Labels: ✨ Feature

#59 Refactor/40/comment
  src/main/java/com/hangout/hangout/domain/comment/controller/CommentController.java
  src/main/java/com/hangout/hangout/domain/comment/domain/repository/CommentRepository.java
  src/main/java/com/hangout/hangout/domain/comment/dto/CommentCreateDto.java
  src/main/java/com/hangout/hangout/domain/comment/dto/CommentReadDto.java
  src/main/java/com/hangout/hangout/domain/comment/dto/CommentRequestDTO.java
  src/main/java/com/hangout/hangout/domain/comment/dto/CommentUpdateDto.java
  src/main/java/com/hangout/hangout/domain/comment/entity/Comment.java
  src/main/java/com/hangout/hangout/domain/comment/service/CommentService.java
  src/main/java/com/hangout/hangout/domain/like/dto/LikeCommentRequest.java
  src/main/java/com/hangout/hangout/domain/like/entity/CommentLike.java
  src/main/java/com/hangout/hangout/domain/like/repository/LikeCommentRepository.java
  src/main/java/com/hangout/hangout/domain/like/service/LikeService.java
  src/main/java/com/hangout/hangout/domain/user/repository/UserRepository.java
  src/main/java/com/hangout/hangout/global/error/ResponseType.java
  src/main/resources/application-oauth.yml
Labels: ✨ Feature, 🔨 Refactor
