Repository Team-hangout/backend, pull requests merged in 2023-11, with the labels that each got.

#74 Refactor/73/map
  src/main/java/com/hangout/hangout/domain/auth/controller/AuthController.java
  src/main/java/com/hangout/hangout/domain/comment/domain/repository/CommentRepositoryQuerydslImpl.java
  src/main/java/com/hangout/hangout/domain/post/PostMapper.java
  src/main/java/com/hangout/hangout/domain/post/controller/PostController.java
  src/main/java/com/hangout/hangout/domain/post/dto/PostListResponse.java
  src/main/java/com/hangout/hangout/domain/post/dto/PostRequest.java
  src/main/java/com/hangout/hangout/domain/post/dto/PostResponse.java
  src/main/java/com/hangout/hangout/domain/post/entity/Map.java
  src/main/java/com/hangout/hangout/domain/post/repository/PostRepositoryQuerydsl.java
  src/main/java/com/hangout/hangout/domain/post/repository/PostRepositoryQuerydslImpl.java
  src/main/java/com/hangout/hangout/domain/post/service/PostService.java
Labels: ✨ Feature, 🔨 Refactor

#75 Fix/66/social login
  src/main/java/com/hangout/hangout/domain/auth/service/AuthService.java
  src/main/java/com/hangout/hangout/global/common/domain/entity/Constants.java
  src/main/java/com/hangout/hangout/global/common/domain/repository/CookieAuthorizationRequestRepository.java
  src/main/java/com/hangout/hangout/global/config/SecurityConfig.java
  src/main/java/com/hangout/hangout/global/config/SwaggerConfig.java
  src/main/java/com/hangout/hangout/global/error/ResponseType.java
  src/main/java/com/hangout/hangout/global/handler/GlobalExceptionHandler.java
  src/main/java/com/hangout/hangout/global/handler/JwtAccessDeniedHandler.java
  src/main/java/com/hangout/hangout/global/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/hangout/hangout/global/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/hangout/hangout/global/security/JwtAuthenticateFilter.java
  src/main/java/com/hangout/hangout/global/security/JwtService.java
  src/main/java/com/hangout/hangout/global/util/CookieUtil.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: 🐞 bug, 🔨 Refactor

#76 Refactor/76/fix
  src/main/java/com/hangout/hangout/domain/image/repository/ImageJdbcRepository.java
  src/main/resources/application.yml
Labels: 🐞 bug
